### ISSUE TITLE
Post publication worker error when processing modules table on cte dev

### ISSUE THREAD

**Issue by karenc** [Connexions/cnx-publishing#137]
```
2016-08-08 16:29:30,616 ERROR [post_publication][MainThread] ident_hash=38367462-cc4a-4445-9b70-f5c767946ee6@1.1 module_ident=165454 error=pop from empty list
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/scripts/post_publication.py", line 57, in process
    collate(binder, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 86, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/collation.py", line 27, in collate
    binder = collate_models(binder)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 77, in collate
    collated_binder = reconstitute(collated_html)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 51, in reconstitute
    return adapt_single_html(xhtml)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 345, in adapt_single_html
    _adapt_single_html_tree(binder, body[0], nav_tree)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 392, in _adapt_single_html_tree
    nav_tree['contents'].pop(0)
IndexError: pop from empty list
```

```
2016-08-08 16:29:38,775 ERROR [post_publication][MainThread] ident_hash=b4aa4ae4-f51e-47da-9938-d3973caf1964@2.1 module_ident=165455 error=pop from empty list
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/scripts/post_publication.py", line 57, in process
    collate(binder, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 86, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/collation.py", line 27, in collate
    binder = collate_models(binder)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 77, in collate
    collated_binder = reconstitute(collated_html)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 51, in reconstitute
    return adapt_single_html(xhtml)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 345, in adapt_single_html
    _adapt_single_html_tree(binder, body[0], nav_tree)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 388, in _adapt_single_html_tree
    nav_tree['contents'].pop(0),
IndexError: pop from empty list
```

**Comment by karenc** [comment]
On cte-cnx-dev.cnx.org, I investigated the error for "Testing ruleset inclusion" `38367462-cc4a-4445-9b70-f5c767946ee6@1.1` and what I found is that after collation, `<nav>` is empty, causing cnxepub reconstitution to fail:

```
karen@cte-cnx-dev:~$ /var/cnx/venvs/archive/bin/cnx-archive-export_epub /etc/cnx/archive/app.ini '38367462-cc4a-4445-9b70-f5c767946ee6@1.1' testing-ruleset-inclusion.epub
karen@cte-cnx-dev:~$ psql -U rhaptos repository
psql (9.4.5)
Type "help" for help.

repository=# \copy (select encode(file, 'escape') from files natural join module_files natural join modules where uuid = '38367462-cc4a-4445-9b70-f5c767946ee6' and filename = 'ruleset.css') to '/home/karen/testing-ruleset-inclusion.css';
COPY 1
repository=# \q
karen@cte-cnx-dev:~$ vim testing-ruleset-inclusion.css  # fix up the \n in the file
karen@cte-cnx-dev:~$ /var/cnx/venvs/publishing/bin/cnx-epub-single_html testing-ruleset-inclusion.epub testing-ruleset-inclusion.html
karen@cte-cnx-dev:~$ /var/cnx/venvs/publishing/bin/cnx-easybake testing-ruleset-inclusion.css testing-ruleset-inclusion.html testing-ruleset-inclusion.collated.html
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 65>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 66>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 66>]
cnx-easybake WARNING title-spans empty bucket
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 66>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 66>]
cnx-easybake WARNING title-spans empty bucket
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 65>]
cnx-easybake WARNING eob-toc empty bucket
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Unknown term <IdentToken none>
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Unknown term <IdentToken none>
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 60>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 50>]
cnx-easybake WARNING eob-index empty bucket
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <NumberToken 100>]
cnx-easybake WARNING Old-style pass as declaration not allowed.[<WhitespaceToken>, <IdentToken default>]
cnx-easybake WARNING trash empty bucket
```

This is the nav in `testing-ruleset-inclusion.html`:

```
   <nav id="toc"><ol><li><a href="cb418599-f69b-46c1-b0ef-60d9e36e677f@6.xhtml">Definitions of Statistics, Probability, and Key Terms</a></li><li><a href="d93df8ff-6e4a-4a5e-befc-ba5a144f309c@11.xhtml">Introduction</a></li></ol></nav>
```

This is the nav in `testing-ruleset-inclusion.collated.html`:

```
<nav id="toc"></nav>
```

**Comment by karenc** [comment]
The ruleset wasn't working with the latest cnx-easybake, seems to be fixed in https://github.com/Connexions/cnx-recipes/pull/40.
