### ISSUE TITLE
Tests failing due to cnx-epub changes

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-publishing#241]
Running the tests produces:
```
E   ConftestImportFailure: (local('/src/cnxpublishing/tests/conftest.py'), (<class 'lxml.etree.XMLSyntaxError'>, XMLSyntaxError(u'Opening and ending tag mismatch: img line 1 and body, line 1, column 114',), <traceback object at 0x7f1656ae3c68>))
```

This strange error is due to:

```pytb
>>> import cnxpublishing.tests.use_cases
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cnxpublishing/tests/use_cases.py", line 134, in <module>
    u'print_style': u'*print style*',
  File "/usr/local/lib/python2.7/site-packages/cnxepub/models.py", line 447, in __init__
    self.content = utf8(data)
  File "/usr/local/lib/python2.7/site-packages/cnxepub/models.py", line 461, in _content__set
    self._xml = content_to_etree(value)
  File "/usr/local/lib/python2.7/site-packages/cnxepub/models.py", line 89, in content_to_etree
    tree = etree.XML(content, xml_parser)
  File "src/lxml/etree.pyx", line 3192, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1758, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: img line 1 and body, line 1, column 114
```

**Comment by pumazi** [comment]
Fixed in 7c5dcd284d5437cdbecb00ad3577438d3554de4b
