### ISSUE TITLE
Duplication resource used in the same document errors

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-publishing#94]
Because we are using the data uri scheme for resources, the normalization of resources within the cnx-epub logic is bypassed. As a result a data integrity error is raised from the database.

```pytb
Traceback (most recent call last):
  ...
  File "/opt/dev/cnx-publishing/cnxpublishing/views.py", line 68, in publish
    state, messages = poke_publication_state(publication_id)
  File "/opt/dev/cnx-publishing/cnxpublishing/db.py", line 97, in wrapped
    return func(*args, **kwargs)
  File "/opt/dev/cnx-publishing/cnxpublishing/db.py", line 866, in poke_publication_state
    publication_state = publish_pending(cursor, publication_id)
  File "/opt/dev/cnx-publishing/cnxpublishing/db.py", line 978, in publish_pending
    ident_hash = publish_model(cursor, document, publisher, message)
  File "/opt/dev/cnx-publishing/cnxpublishing/publish.py", line 287, in publish_model
    _insert_resource_file(cursor, module_ident, resource)
  File "/opt/dev/cnx-publishing/cnxpublishing/publish.py", line 221, in _insert_resource_file
    VALUES (%s, %s, %s, %s)""", args)
IntegrityError: duplicate key value violates unique constraint "module_files_idx"
DETAIL:  Key (module_ident, filename)=(119140, 9631bb0341681c6f5281bab2cbd8b1f8b53f477e) already exists.
```

Reproducible by including the same image (in data-uri format) twice within a document.

**Comment by reedstrm** [comment]
If those filenames are sha1 hashes, then the file is identical, so we can just skip storing it.

**Comment by edwoodward** [comment]
This is not working on dev as of this morning.
